#! /bin/sh
rm -rf /Users/andreyvit/Projects/ecabu/build
date="$(date '+%Y%m%d-%H%M')"
ruby ecabu.rb --binary /Applications/Eclipse\ 3.3.app/Contents/Resources/Java/plugins --qualifier "YS$date" --source ~/Projects/YourSway/dltk-yoursway/core/plugins --qualifier "N$date" --source ~/Projects/EskoArtwork/antlr --include-following --source ~/Projects/EskoArtwork/esko --output /Users/andreyvit/Projects/ecabu/build --exclude '*tests*' --include 'org.eclipse.swt.*'
